### ISSUE TITLE
Can you update possum to awesome-possum on creating app package.json?

### ISSUE THREAD

**Issue by EricLow525** [revelrylabs/slush-revelry#9]
I've created my new app using `slush revelry:new my-app-name`.
And then I've installed npm, but there is one issue.
```
npm ERR! notarget No compatible version found: possum@^3.0.0
```

so I changed possum to awesome-possum on package.json manually.
This will confuse many users.

**Comment by prehnRA** [comment]
Good catch! I've updated that in the latest version (published as 1.0.1 & available on the v1.0.1 tag / master here).

Thanks for submitting this.

**Comment by EricLow525** [comment]
Hi Robert,
I hope you are doing well.
Thanks for your message.

What is next step?

Best,
Eric.

**Comment by EricLow525** [comment]
Hi @prehnRA 
I've run `npm run dev` command line on my terminal.
It did not work because there are some errors.

```
> my-app-name@1.0.0 dev /Volumes/Data/Work/my-app-name
> gulp build && gulp dev

[18:14:21] Using gulpfile /Volumes/Data/Work/my-app-name/gulpfile.js
[18:14:21] Starting 'webpack'...
[18:14:21] Starting 'sass'...
[18:14:21] Starting 'statics'...
[18:14:21] Finished 'statics' after 3.27 ms
Error in plugin 'sass'
Message:
    src/css/site.scss
Error: File to import not found or unreadable: CardLayout.
       Parent style sheet: /Volumes/Data/Work/my-app-name/src/css/site.scss
        on line 3 of src/css/site.scss
>> @import 'CardLayout';
   ^

[18:14:28] Finished 'sass' after 6.85 s
{ Error: Cannot resolve module 'possum/lib/Tabs' in /Volumes/Data/Work/my-app-name/src/js/app/examples/views
    at innerCallback (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/Resolver.js:91:16)
    at loggingCallbackWrapper (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Volumes/Data/Work/my-app-name/node_modules/tapable/lib/Tapable.js:134:6
    at /Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:54:23
    at /Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:45:26
    at loggingCallbackWrapper (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Volumes/Data/Work/my-app-name/node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/ModuleAsDirectoryPlugin.js:30:12)
    at Storage.finished (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
  details: 'resolve module possum/lib/Tabs in /Volumes/Data/Work/my-app-name/src/js/app/examples/views\n  looking for modules in /Volumes/Data/Work/my-app-name/src/js\n    /Volumes/Data/Work/my-app-name/src/js/possum doesn\'t exist (module as directory)\n  looking for modules in /Volumes/Data/Work/my-app-name/node_modules\n    /Volumes/Data/Work/my-app-name/node_modules/possum doesn\'t exist (module as directory)',
  missing:
   [ '/Volumes/Data/Work/my-app-name/src/js/possum',
     '/Volumes/Data/Work/my-app-name/node_modules/possum' ] }
ERROR: Webpack build failed.
[18:14:31] Finished 'webpack' after 9.82 s
[18:14:31] Starting 'build'...
[18:14:31] Finished 'build' after 4.82 ms
[18:14:57] Using gulpfile /Volumes/Data/Work/my-app-name/gulpfile.js
[18:14:57] Starting 'serve:watch'...
[18:14:58] Finished 'serve:watch' after 1.38 s
[18:14:58] Starting 'webpack'...
[18:14:58] Starting 'sass:watch'...
[18:14:58] Finished 'sass:watch' after 19 ms
[18:14:58] Starting 'statics:watch'...
[18:14:58] Finished 'statics:watch' after 28 ms
[18:14:58] Starting 'dist:watch'...
[18:14:58] Finished 'dist:watch' after 12 ms
[18:14:58] [nodemon] 1.14.11
[18:14:58] [nodemon] to restart at any time, enter `rs`
[18:14:58] [nodemon] watching: /Volumes/Data/Work/my-app-name/dist/**/*
[18:14:58] [nodemon] starting `node /Volumes/Data/Work/my-app-name/dist/server.js`
module.js:471
    throw err;
    ^

Error: Cannot find module '/Volumes/Data/Work/my-app-name/dist/server.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
[18:14:59] [nodemon] app crashed - waiting for file changes before starting...
{ Error: Cannot resolve module 'possum/lib/Tabs' in /Volumes/Data/Work/my-app-name/src/js/app/examples/views
    at innerCallback (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/Resolver.js:91:16)
    at loggingCallbackWrapper (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Volumes/Data/Work/my-app-name/node_modules/tapable/lib/Tapable.js:134:6
    at /Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:54:23
    at /Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:45:26
    at loggingCallbackWrapper (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Volumes/Data/Work/my-app-name/node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/ModuleAsDirectoryPlugin.js:30:12)
    at Storage.finished (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
  details: 'resolve module possum/lib/Tabs in /Volumes/Data/Work/my-app-name/src/js/app/examples/views\n  looking for modules in /Volumes/Data/Work/my-app-name/src/js\n    /Volumes/Data/Work/my-app-name/src/js/possum doesn\'t exist (module as directory)\n  looking for modules in /Volumes/Data/Work/my-app-name/node_modules\n    /Volumes/Data/Work/my-app-name/node_modules/possum doesn\'t exist (module as directory)',
  missing:
   [ '/Volumes/Data/Work/my-app-name/src/js/possum',
     '/Volumes/Data/Work/my-app-name/node_modules/possum' ] }
ERROR: Webpack build failed.
[18:15:08] Finished 'webpack' after 9.58 s
[18:15:08] Starting 'webpack:watch'...
{ Error: Cannot resolve module 'possum/lib/Tabs' in /Volumes/Data/Work/my-app-name/src/js/app/examples/views
    at innerCallback (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/Resolver.js:91:16)
    at loggingCallbackWrapper (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Volumes/Data/Work/my-app-name/node_modules/tapable/lib/Tapable.js:134:6
    at /Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:54:23
    at /Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at Tapable.<anonymous> (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:50:12)
    at Storage.provide (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:52:20)
    at CachedInputFileSystem.stat (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:132:20)
    at Tapable.<anonymous> (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:36:7)
    at Tapable.Resolver.forEachBail (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/Resolver.js:196:3)
  details: 'resolve module possum/lib/Tabs in /Volumes/Data/Work/my-app-name/src/js/app/examples/views\n  looking for modules in /Volumes/Data/Work/my-app-name/src/js\n    /Volumes/Data/Work/my-app-name/src/js/possum doesn\'t exist (module as directory)\n  looking for modules in /Volumes/Data/Work/my-app-name/node_modules\n    /Volumes/Data/Work/my-app-name/node_modules/possum doesn\'t exist (module as directory)',
  missing:
   [ '/Volumes/Data/Work/my-app-name/src/js/possum',
     '/Volumes/Data/Work/my-app-name/node_modules/possum' ] }
ERROR: Webpack build failed.
[18:15:10] Finished 'webpack:watch' after 1.71 s
[18:15:10] Starting 'dev'...
[18:15:10] Finished 'dev' after 3.46 μs
{ Error: Cannot resolve module 'possum/lib/Tabs' in /Volumes/Data/Work/my-app-name/src/js/app/examples/views
    at innerCallback (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/Resolver.js:91:16)
    at loggingCallbackWrapper (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Volumes/Data/Work/my-app-name/node_modules/tapable/lib/Tapable.js:134:6
    at /Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:54:23
    at /Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:45:26
    at loggingCallbackWrapper (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Volumes/Data/Work/my-app-name/node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/ModuleAsDirectoryPlugin.js:30:12)
    at Storage.finished (/Volumes/Data/Work/my-app-name/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
  details: 'resolve module possum/lib/Tabs in /Volumes/Data/Work/my-app-name/src/js/app/examples/views\n  looking for modules in /Volumes/Data/Work/my-app-name/src/js\n    /Volumes/Data/Work/my-app-name/src/js/possum doesn\'t exist (module as directory)\n  looking for modules in /Volumes/Data/Work/my-app-name/node_modules\n    /Volumes/Data/Work/my-app-name/node_modules/possum doesn\'t exist (module as directory)',
  missing:
   [ '/Volumes/Data/Work/my-app-name/src/js/possum',
     '/Volumes/Data/Work/my-app-name/node_modules/possum' ] }
ERROR: Webpack build failed.
```

**Comment by EricLow525** [comment]
Could you tell me how I can fix those issues?
